### ISSUE TITLE
.phy files not appearing/uploading on shinyPhry

### ISSUE THREAD

**Issue by bbanbury** [bbanbury/phrynomics#2]
Some work, some don't

**Comment by lixingguang** [comment]
@bbanbury, which format of phy should I loaded into the readsnp (). I tried many times , but failed.

**Comment by bbanbury** [comment]
Are you using the package or the shiny site?  
If you are using the package, you should be able to use any data.frame or matrix if it is already read into R.  If you want to import a file, you can also do that, but it needs to be phylip or nexus formatted. You can also look at the fakeData object to see how it is formatted (it comes with the package).

**Comment by bbanbury** [comment]
@lixingguang can you open a new issue please? I'm going to close the old ones.
